Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,7 +1,7 @@
-# This workflow will build a golang project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
-
 name: Go
+
+env:
+  GIN_MODE: release
 
 on:
   push:
@@ -10,19 +10,40 @@ on:
     branches: [ "main" ]
 
 jobs:
-
   build:
     runs-on: ubuntu-latest
+
+    permissions:
+      checks: write
+
     steps:
     - uses: actions/checkout@v3
 
     - name: Set up Go
-      uses: actions/setup-go@v4
+      uses: actions/setup-go@v3
       with:
-        go-version: '1.20'
+        go-version-file: 'go.mod'
+        cache: true
+
+    - name: Revive Action
+      uses: morphy2k/revive-action@v2.4.1
+
+    - name: Staticcheck
+      uses: dominikh/staticcheck-action@v1.3.0
 
     - name: Build
-      run: go build -v ./...
+      run: |
+        go mod download
+        go install gotest.tools/gotestsum@latest
 
     - name: Test
-      run: go test -v ./...
+      run: |
+        gotestsum --format=standard-verbose --junitfile=junit.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
